#!/usr/bin/env ruby

#    Copyright (c) 2015, Simon Schubert <2@0x2c.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'dnssd'

def recv(res)
  filename = res.text_record['file']
  puts "pulling #{filename}"

  if File.exist? filename
    $stderr.puts "#{filename} already exists"
    exit 1
  end

  File.open(filename, File::WRONLY | File::CREAT | File::EXCL) do |outf|
    conn = res.connect()
    puts "connected to #{res.target}"
    recvd = 0
    while !conn.eof
      buf = conn.read(1024*1024)
      outf.write(buf)
      recvd += buf.bytesize
      print "\rreceived #{recvd} bytes..."
    end
    conn.close
    puts "done."
  end
end

puts "searching for shared files"
DNSSD.browse!('_localfileshare._tcp') do |reply|
  puts "#{reply.name} is advertising"
  DNSSD.resolve!(reply) do |res|
    recv(res)
    exit 0
  end
end
