#!/usr/bin/env ruby

#    Copyright (c) 2015, Simon Schubert <2@0x2c.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'dnssd'
require 'etc'
require 'socket'

filename = ARGV[0]

if !filename
  $stderr.puts "usage: share <file>"
  exit 1
end

servname = "%s on %s" % [Etc.getlogin, Socket.gethostname]

begin
  port = rand(5535) + 60000
  servsock = TCPServer.new(port)
rescue Errno::EADDRINUSE
  retry
end

File.open(filename, 'r') do |file|
  announcename = File.basename(filename)
  puts "sharing #{announcename}"

  info = DNSSD::TextRecord.new 'file' => announcename
  DNSSD.announce(servsock, servname, "localfileshare", info)

  puts "waiting for connection"
  connsock = servsock.accept
  clientname = connsock.remote_address.getnameinfo.first
  puts "connection from #{clientname}"
  sent = 0
  while !file.eof
    buf = file.read(1024*1024)
    connsock.write(buf)
    sent += buf.bytesize
    print "\rsent #{sent} bytes..."
  end
  connsock.shutdown
  puts " done."
end

servsock.close
